/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SwitcherList {
    }
}
declare global {
    interface HTMLSwitcherListElement extends Components.SwitcherList, HTMLStencilElement {
    }
    var HTMLSwitcherListElement: {
        prototype: HTMLSwitcherListElement;
        new (): HTMLSwitcherListElement;
    };
    interface HTMLElementTagNameMap {
        "switcher-list": HTMLSwitcherListElement;
    }
}
declare namespace LocalJSX {
    interface SwitcherList {
    }
    interface IntrinsicElements {
        "switcher-list": SwitcherList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "switcher-list": LocalJSX.SwitcherList & JSXBase.HTMLAttributes<HTMLSwitcherListElement>;
        }
    }
}
